services:
  opendt:
    entrypoint: ["python", "-u", "-m", "opendt.cli"]  # Commented out for interactive mode
    # command: sleep infinity
    environment:
      - OPENDT_DATA_DIR=/app/data
      - OPENDT_SIM_DIR=/app/output/opendt-simulation/raw-output
      - OPENDT_LOG_LEVEL=DEBUG
    volumes:
      - ./:/app
      - ./output/opendt-simulation/raw-output:/app/output/opendt-simulation/raw-output
