workload: "SURF"

simulation:
  # 1.0 = Realtime, -1 = Max Speed
  speed_factor: 300
  window_size_minutes: 5

features:
  calibration_enabled: false

kafka:
  bootstrap_servers: "kafka:29092"
  topics:
    workload:
      name: "dc.workload"
      config:
        # 24 hours
        retention.ms: "86400000"
    power:
      name: "dc.power"
      config:
        # 1 hour
        retention.ms: "3600000"
    system:
      name: "sys.config"
      config:
        cleanup.policy: "compact"
